<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nicholas Lisac">
<meta name="dcterms.date" content="2026-06-15">
<meta name="keywords" content="time series forecasting, foundation models, traffic prediction, SARIMA, zero-shot learning, uncertainty calibration, CPM">

<title>Zero-Shot Foundation Models Outperform Classical Methods on Roadway Traffic Forecasting</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="paper_files/libs/clipboard/clipboard.min.js"></script>
<script src="paper_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="paper_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="paper_files/libs/quarto-html/popper.min.js"></script>
<script src="paper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="paper_files/libs/quarto-html/anchor.min.js"></script>
<link href="paper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="paper_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="paper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="paper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="paper_files/libs/bootstrap/bootstrap-67270d1595a62d14f123c043d4fb2f18.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


<link rel="stylesheet" href="styles.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#contributions" id="toc-contributions" class="nav-link" data-scroll-target="#contributions"><span class="header-section-number">1.1</span> Contributions</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">2</span> Data</a>
  <ul class="collapse">
  <li><a href="#source-and-collection" id="toc-source-and-collection" class="nav-link" data-scroll-target="#source-and-collection"><span class="header-section-number">2.1</span> Source and Collection</a></li>
  <li><a href="#traintest-split" id="toc-traintest-split" class="nav-link" data-scroll-target="#traintest-split"><span class="header-section-number">2.2</span> Train/Test Split</a></li>
  <li><a href="#data-characteristics" id="toc-data-characteristics" class="nav-link" data-scroll-target="#data-characteristics"><span class="header-section-number">2.3</span> Data Characteristics</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">3</span> Methods</a>
  <ul class="collapse">
  <li><a href="#evaluation-protocol" id="toc-evaluation-protocol" class="nav-link" data-scroll-target="#evaluation-protocol"><span class="header-section-number">3.1</span> Evaluation Protocol</a></li>
  <li><a href="#classical-models" id="toc-classical-models" class="nav-link" data-scroll-target="#classical-models"><span class="header-section-number">3.2</span> Classical Models</a>
  <ul class="collapse">
  <li><a href="#sarima" id="toc-sarima" class="nav-link" data-scroll-target="#sarima"><span class="header-section-number">3.2.1</span> SARIMA</a></li>
  <li><a href="#mstl-arima" id="toc-mstl-arima" class="nav-link" data-scroll-target="#mstl-arima"><span class="header-section-number">3.2.2</span> MSTL + ARIMA</a></li>
  <li><a href="#seasonal-naive" id="toc-seasonal-naive" class="nav-link" data-scroll-target="#seasonal-naive"><span class="header-section-number">3.2.3</span> Seasonal Naive</a></li>
  </ul></li>
  <li><a href="#toto-2.0-2.5b" id="toc-toto-2.0-2.5b" class="nav-link" data-scroll-target="#toto-2.0-2.5b"><span class="header-section-number">3.3</span> Toto-2.0-2.5B</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4</span> Results</a>
  <ul class="collapse">
  <li><a href="#hourly-forecast-performance" id="toc-hourly-forecast-performance" class="nav-link" data-scroll-target="#hourly-forecast-performance"><span class="header-section-number">4.1</span> Hourly Forecast Performance</a></li>
  <li><a href="#daily-forecast-performance" id="toc-daily-forecast-performance" class="nav-link" data-scroll-target="#daily-forecast-performance"><span class="header-section-number">4.2</span> Daily Forecast Performance</a></li>
  <li><a href="#forecast-visualizations" id="toc-forecast-visualizations" class="nav-link" data-scroll-target="#forecast-visualizations"><span class="header-section-number">4.3</span> Forecast Visualizations</a></li>
  <li><a href="#per-window-stability" id="toc-per-window-stability" class="nav-link" data-scroll-target="#per-window-stability"><span class="header-section-number">4.4</span> Per-Window Stability</a></li>
  <li><a href="#uncertainty-calibration" id="toc-uncertainty-calibration" class="nav-link" data-scroll-target="#uncertainty-calibration"><span class="header-section-number">4.5</span> Uncertainty Calibration</a></li>
  <li><a href="#horizon-stress-test-cpm-error-growth" id="toc-horizon-stress-test-cpm-error-growth" class="nav-link" data-scroll-target="#horizon-stress-test-cpm-error-growth"><span class="header-section-number">4.6</span> Horizon Stress-Test: CPM Error Growth</a>
  <ul class="collapse">
  <li><a href="#cpm-stress-test-rolling-windows" id="toc-cpm-stress-test-rolling-windows" class="nav-link" data-scroll-target="#cpm-stress-test-rolling-windows"><span class="header-section-number">4.6.1</span> CPM Stress-Test (Rolling Windows)</a></li>
  <li><a href="#single-origin-comparison-no-re-scoring" id="toc-single-origin-comparison-no-re-scoring" class="nav-link" data-scroll-target="#single-origin-comparison-no-re-scoring"><span class="header-section-number">4.6.2</span> Single-Origin Comparison (No Re-Scoring)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">5</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#why-toto-outperformed" id="toc-why-toto-outperformed" class="nav-link" data-scroll-target="#why-toto-outperformed"><span class="header-section-number">5.1</span> Why Toto Outperformed</a>
  <ul class="collapse">
  <li><a href="#scaling-laws-for-time-series" id="toc-scaling-laws-for-time-series" class="nav-link" data-scroll-target="#scaling-laws-for-time-series"><span class="header-section-number">5.1.1</span> Scaling Laws for Time Series</a></li>
  <li><a href="#sliding-window-adaptation" id="toc-sliding-window-adaptation" class="nav-link" data-scroll-target="#sliding-window-adaptation"><span class="header-section-number">5.1.2</span> Sliding Window Adaptation</a></li>
  <li><a href="#patch-based-architecture-with-long-context" id="toc-patch-based-architecture-with-long-context" class="nav-link" data-scroll-target="#patch-based-architecture-with-long-context"><span class="header-section-number">5.1.3</span> Patch-Based Architecture with Long Context</a></li>
  <li><a href="#well-calibrated-cross-domain-uncertainty" id="toc-well-calibrated-cross-domain-uncertainty" class="nav-link" data-scroll-target="#well-calibrated-cross-domain-uncertainty"><span class="header-section-number">5.1.4</span> Well-Calibrated Cross-Domain Uncertainty</a></li>
  <li><a href="#sliding-window-the-key-to-production-advantage" id="toc-sliding-window-the-key-to-production-advantage" class="nav-link" data-scroll-target="#sliding-window-the-key-to-production-advantage"><span class="header-section-number">5.1.5</span> Sliding Window: The Key to Production Advantage</a></li>
  </ul></li>
  <li><a href="#why-classical-methods-underperformed" id="toc-why-classical-methods-underperformed" class="nav-link" data-scroll-target="#why-classical-methods-underperformed"><span class="header-section-number">5.2</span> Why Classical Methods Underperformed</a>
  <ul class="collapse">
  <li><a href="#sarimas-parametric-constraints" id="toc-sarimas-parametric-constraints" class="nav-link" data-scroll-target="#sarimas-parametric-constraints"><span class="header-section-number">5.2.1</span> SARIMA’s Parametric Constraints</a></li>
  <li><a href="#mstlarima-daily-degradation" id="toc-mstlarima-daily-degradation" class="nav-link" data-scroll-target="#mstlarima-daily-degradation"><span class="header-section-number">5.2.2</span> MSTL+ARIMA Daily Degradation</a></li>
  <li><a href="#no-test-period-adaptation" id="toc-no-test-period-adaptation" class="nav-link" data-scroll-target="#no-test-period-adaptation"><span class="header-section-number">5.2.3</span> No Test-Period Adaptation</a></li>
  </ul></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">5.3</span> Limitations</a></li>
  <li><a href="#broader-implications" id="toc-broader-implications" class="nav-link" data-scroll-target="#broader-implications"><span class="header-section-number">5.4</span> Broader Implications</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">6</span> Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">7</span> References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="paper.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Zero-Shot Foundation Models Outperform Classical Methods on Roadway Traffic Forecasting</h1>
<p class="subtitle lead">A Comparative Study of Toto-2.0-2.5B vs SARIMA, MSTL+ARIMA, and Seasonal Naive</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nicholas Lisac </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 15, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>We evaluate whether a 2.5B-parameter time series foundation model, trained on observability metrics and deployed zero-shot (no fine-tuning), can compete with classical statistical methods on roadway traffic volume forecasting. Using 6.5 years of hourly traffic counts from a single MaineDOT sensor, we compare SARIMA, MSTL+ARIMA, seasonal naive, and Toto-2.0-2.5B across hourly and daily forecast horizons. With full-year context (8,704 hours) for fair comparison, Toto-2.5B achieves the lowest error on both horizons: MAE of 46.5 vehicles/hour (hourly) and 859 vehicles/day (daily), outperforming the strongest classical baseline (MSTL+ARIMA) by 19.0% and 66.7% respectively. Toto’s 80% prediction intervals achieve 82.3% empirical coverage (ECE = 2.3%), demonstrating that uncertainty calibration transfers across domains. Horizon stress-testing up to 4 weeks reveals that Toto dominates at 1-week horizons (31.6 vs.&nbsp;45.2 MAE) but degrades faster than AR models at 2-3 weeks (273.6 vs.&nbsp;75.7), demonstrating that the sliding-window protocol (re-scoring every 24h with fresh context) is the practical mechanism converting short-horizon dominance into sustained accuracy. Rolling-window average across 158 origins yields a 1-week MAE of 59.2, confirming sustained competitiveness. Inference time is flat at 0.2s/window regardless of horizon length, confirming CPM’s O(1) decoding. These results demonstrate that scaling laws for time series foundation models enable genuine cross-domain generalization of both point accuracy and uncertainty structure, and that long context windows are critical for capturing seasonal patterns in traffic data.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>time series forecasting, foundation models, traffic prediction, SARIMA, zero-shot learning, uncertainty calibration, CPM</p>
  </div>
</div>

</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Time series forecasting has been dominated by classical statistical methods for decades. Models like SARIMA (Seasonal AutoRegressive Integrated Moving Average) and TBATS (Trigonometric seasonality, Box-Cox transformation, ARMA errors, Trend, and Seasonal components) are the workhorses of production forecasting systems, particularly for data with strong seasonal patterns.</p>
<p>The emergence of large language models has catalyzed a parallel development in time series: <strong>foundation models</strong> trained on trillions of time series tokens across diverse domains. Datadog’s Toto-2.0-2.5B represents the state of the art—a 2.5B-parameter decoder-only transformer trained on over 2 trillion time series data points from observability metrics (CPU utilization, request latency, error rates, database performance).</p>
<p>This raises a critical question: <strong>can a foundation model generalize to domains outside its training distribution?</strong> Roadway traffic counts are structurally different from server metrics—sharper peaks, stronger periodicity, different noise characteristics, and magnitude scales (~100-1400 vehicles/hour vs.&nbsp;0-100% utilization).</p>
<p>We test this on 6.5 years of hourly traffic data from a MaineDOT sensor, comparing Toto-2.0-2.5B (zero-shot, no fine-tuning) against SARIMA, MSTL+ARIMA, and seasonal naive. Our results challenge the assumption that classical methods dominate on clean seasonal data.</p>
<section id="contributions" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="contributions"><span class="header-section-number">1.1</span> Contributions</h2>
<ol type="1">
<li><strong>First comprehensive comparison</strong> of Toto-2.0-2.5B against classical methods on roadway traffic data with full context parity</li>
<li><strong>Rolling evaluation protocol</strong> that fairly compares sliding-window foundation models against re-fitted classical models</li>
<li><strong>Evidence of cross-domain generalization</strong>: Toto-2.5B outperforms all baselines despite zero traffic-domain training</li>
<li><strong>Context length matters</strong>: Demonstrating that 8,704-hour context improves Toto’s MAE by 12% over 320-hour context</li>
<li><strong>Sliding-window protocol analysis</strong>: Showing that Toto’s production advantage comes from continuous re-scoring, not single-origin accuracy</li>
<li><strong>Open pipeline</strong>: All code, data, and results are reproducible</li>
</ol>
</section>
</section>
<section id="data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data</h1>
<section id="source-and-collection" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="source-and-collection"><span class="header-section-number">2.1</span> Source and Collection</h2>
<p><strong>Sensor</strong>: MaineDOT Site 133119702600—OGUNQUIT 02600 (US 1 @ BR# 2239 @ WELLS TL)</p>
<p><strong>Granularity</strong>: Hourly vehicle counts across 6 directional lanes (All Directions, All Northbound, All Southbound, Lane 1 NB, Center Turn Lane, Lane 1 SB)</p>
<p><strong>Period</strong>: January 1, 2020 → June 14, 2026 (2,357 days, 56,568 hours)</p>
<p>The Drakewell C2 platform serves 35-day rolling windows of hourly traffic data as HTML tables. No public API exists. Data was collected via headless browser scraping (Playwright) with 0.5-second delays between requests to avoid rate limiting. 68 overlapping requests (35-day windows, advancing 1 day each) covered the full date range, yielding 395,976 unique hourly records after deduplication.</p>
</section>
<section id="traintest-split" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="traintest-split"><span class="header-section-number">2.2</span> Train/Test Split</h2>
<div id="6376e7af" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>| Split   | Period                  |   Hours |   Days |
|:--------|:------------------------|--------:|-------:|
| Train   | 2020-01-01 → 2025-12-31 |   52608 |   2192 |
| Test    | 2026-01-01 → 2026-06-13 |    3936 |    164 |</code></pre>
</div>
</div>
<p>The train/test split respects temporal ordering—no look-ahead bias. The test period captures seasonal transition (winter to summer), providing a challenging evaluation setting.</p>
</section>
<section id="data-characteristics" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="data-characteristics"><span class="header-section-number">2.3</span> Data Characteristics</h2>
<div id="cell-data-stats" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.dates <span class="im">as</span> mdates</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load full hourly data for analysis</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>full_data <span class="op">=</span> pd.read_csv(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"data/series/r_hourly_full_all_directions.csv"</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>full_data[<span class="st">"datetime"</span>] <span class="op">=</span> pd.to_datetime(</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    full_data[<span class="st">"datetime"</span>], utc<span class="op">=</span><span class="va">True</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Split train/test</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>train_mask <span class="op">=</span> full_data[<span class="st">"datetime"</span>] <span class="op">&lt;=</span> <span class="st">"2025-12-31 23:59:59"</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>test_mask <span class="op">=</span> full_data[<span class="st">"datetime"</span>] <span class="op">&gt;=</span> <span class="st">"2026-01-01"</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel A: Full series</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    full_data[<span class="st">"datetime"</span>], full_data[<span class="st">"value"</span>],</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="fl">0.3</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, color<span class="op">=</span><span class="st">"#2563eb"</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axvline(</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    pd.Timestamp(<span class="st">"2026-01-01"</span>, tz<span class="op">=</span><span class="st">"UTC"</span>),</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"red"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, alpha<span class="op">=</span><span class="fl">0.5</span>,</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"Test start"</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"Vehicles/hour"</span>)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Full 6.5-year series"</span>)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].grid(alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel B: Test period zoom</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>    full_data.loc[test_mask, <span class="st">"datetime"</span>],</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    full_data.loc[test_mask, <span class="st">"value"</span>],</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="fl">0.8</span>, color<span class="op">=</span><span class="st">"#dc2626"</span></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"Vehicles/hour"</span>)</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Test period (2026)"</span>)</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].grid(alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel C: Hour-of-day pattern (train average)</span></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>hourly_pattern <span class="op">=</span> full_data.loc[train_mask].copy()</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>hourly_pattern[<span class="st">"hour"</span>] <span class="op">=</span> hourly_pattern[<span class="st">"datetime"</span>].dt.hour</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>avg_by_hour <span class="op">=</span> hourly_pattern.groupby(<span class="st">"hour"</span>)[<span class="st">"value"</span>].mean()</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].bar(</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>    avg_by_hour.index, avg_by_hour.values,</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"#2563eb"</span>, alpha<span class="op">=</span><span class="fl">0.8</span></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_xlabel(<span class="st">"Hour of day (UTC)"</span>)</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_ylabel(<span class="st">"Avg vehicles/hour"</span>)</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_title(<span class="st">"Daily seasonality pattern (training)"</span>)</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].grid(alpha<span class="op">=</span><span class="fl">0.3</span>, axis<span class="op">=</span><span class="st">"y"</span>)</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>plt.savefig(</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>    <span class="st">"data/plots/data_characteristics.png"</span>,</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>    dpi<span class="op">=</span><span class="dv">200</span>, bbox_inches<span class="op">=</span><span class="st">"tight"</span></span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="data-stats" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="paper_files/figure-html/data-stats-output-1.png" width="952" height="758" class="figure-img"></p>
<figcaption>Traffic volume distribution and seasonal patterns</figcaption>
</figure>
</div>
</div>
</div>
<p>The data exhibits strong daily seasonality (morning/evening commute peaks), weekly patterns (lower weekend volumes), and seasonal trends (higher summer traffic). These characteristics make it a “textbook” case for classical seasonal models—and thus a stringent test for zero-shot generalization.</p>
</section>
</section>
<section id="methods" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Methods</h1>
<section id="evaluation-protocol" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="evaluation-protocol"><span class="header-section-number">3.1</span> Evaluation Protocol</h2>
<p>To ensure fair comparison between sliding-window foundation models and classical methods, we adopt a <strong>rolling evaluation protocol</strong>:</p>
<p><strong>Hourly forecasts</strong>: The test period (3,912 hours) is divided into 24 chunks of 168 hours (1 week) each. For each chunk: - R models are fitted on the most recent 8,760 hours (1 year) of context (training + previously observed test data) - Toto forecasts using 8,704 hours (272 patches) of context, 160 hours horizon, sliding 24 hours - Forecasts are concatenated and evaluated pointwise against actuals</p>
<p><strong>Daily forecasts</strong>: Hourly forecasts are aggregated to daily totals. R models are fitted once on the full training series. Toto’s hourly forecasts are summed in 24-hour blocks.</p>
<p>This protocol matches Toto’s sliding-window setup while giving R models the advantage of full historical context—a conservative design that favors classical methods.</p>
</section>
<section id="classical-models" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="classical-models"><span class="header-section-number">3.2</span> Classical Models</h2>
<section id="sarima" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="sarima"><span class="header-section-number">3.2.1</span> SARIMA</h3>
<p>Fitted via <code>forecast::auto.arima</code> with <code>frequency=24</code>. The optimal order ARIMA(2,0,2)(2,1,0)[24] was identified on the last year of training data, then applied to all rolling chunks to avoid repeated stepwise search. This order captures daily seasonality with seasonal differencing and ARMA errors.</p>
</section>
<section id="mstl-arima" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="mstl-arima"><span class="header-section-number">3.2.2</span> MSTL + ARIMA</h3>
<p>Multiple Seasonal and Trend decomposition using Loess (<code>forecast::stlm</code>), with <code>msts(seasonal.periods = c(24, 168))</code> capturing both daily and weekly cycles. Loess smoothing decomposes the series deterministically; ARIMA is fitted on the non-seasonal remainder. Replaces TBATS for computational efficiency (0.5s vs 2min per chunk) while maintaining accuracy.</p>
</section>
<section id="seasonal-naive" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="seasonal-naive"><span class="header-section-number">3.2.3</span> Seasonal Naive</h3>
<p>The strongest baseline for seasonal data: forecasts each point as the value from the same hour 24 hours prior. Any model worse than naive fails to capture basic seasonality.</p>
</section>
</section>
<section id="toto-2.0-2.5b" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="toto-2.0-2.5b"><span class="header-section-number">3.3</span> Toto-2.0-2.5B</h2>
<p>Toto is a 2.5B-parameter decoder-only transformer trained on 2+ trillion time series tokens. Key configuration:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 24%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
<th>Rationale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Context length</td>
<td>8,704 hours (~1 year)</td>
<td>Matches R models’ context for fairness; 272 patches × 32</td>
</tr>
<tr class="even">
<td>Horizon</td>
<td>160 hours (~6.7 days)</td>
<td>Divisible by patch_size=32</td>
</tr>
<tr class="odd">
<td>Patch size</td>
<td>32</td>
<td>Model architecture constraint</td>
</tr>
<tr class="even">
<td>Windows</td>
<td>158</td>
<td>Sliding 24h across test period</td>
</tr>
<tr class="odd">
<td>Device</td>
<td>RTX 3090 (24GB VRAM)</td>
<td>~0.2s/forecast, CUDA_VISIBLE_DEVICES=2</td>
</tr>
<tr class="even">
<td>Fine-tuning</td>
<td>None</td>
<td>Zero-shot evaluation</td>
</tr>
</tbody>
</table>
<p>The model processes time series through alternating time and variate attention layers, enabling it to capture both temporal dependencies and cross-variate relationships. For the univariate setting, only the “All Directions” aggregated series is provided.</p>
</section>
</section>
<section id="results" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results</h1>
<section id="hourly-forecast-performance" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="hourly-forecast-performance"><span class="header-section-number">4.1</span> Hourly Forecast Performance</h2>
<div id="hourly-table" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>| Model          |   MAE |   RMSE |   MAPE% |   sMAPE% |
|:---------------|------:|-------:|--------:|---------:|
| SARIMA         | 104.7 |  192.6 |    39.5 |     41.8 |
| MSTL+ARIMA     |  57.4 |   89.8 |    33.9 |     28.1 |
| Seasonal Naive |  74.2 |  117.9 |    32.4 |     26.2 |
| Toto-2.5B      |  46.5 |   94.8 |    19.5 |     16.9 |</code></pre>
</div>
</div>
<p><strong>Key finding</strong>: Toto-2.5B achieves the lowest MAE (46.5), outperforming MSTL+ARIMA (57.4) by 19.0% and SARIMA (104.7) by 55.6%. The margin on MAPE is even larger: 19.5% vs 33.9% (MSTL+ARIMA) and 39.5% (SARIMA).</p>
</section>
<section id="daily-forecast-performance" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="daily-forecast-performance"><span class="header-section-number">4.2</span> Daily Forecast Performance</h2>
<div id="daily-table" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>| Model          |    MAE |   RMSE |   MAPE% |   sMAPE% |
|:---------------|-------:|-------:|--------:|---------:|
| SARIMA         | 2839.4 | 3259.6 |    36.6 |     27.8 |
| MSTL+ARIMA     | 2577.8 | 2979.2 |    32.4 |     25.4 |
| Seasonal Naive | 3154.6 | 4269.7 |    32.7 |     31.8 |
| Toto-2.5B      |  859   | 1701   |    10.6 |      9.7 |</code></pre>
</div>
</div>
<p>The daily margin is decisive: Toto’s MAE of 859 vehicles/day is <strong>66.7% lower</strong> than MSTL+ARIMA (2,578) and <strong>69.8% lower</strong> than SARIMA (2,839). This large gap reflects error accumulation in classical methods when summing 24 hourly forecasts, combined with Toto’s ability to capture full-year seasonal patterns with 8,704 hours of context.</p>
</section>
<section id="forecast-visualizations" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="forecast-visualizations"><span class="header-section-number">4.3</span> Forecast Visualizations</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="data/plots/hourly_comparison.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Hourly forecast comparison</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="data/plots/hourly_pattern.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Hourly pattern comparison</figcaption>
</figure>
</div>
</section>
<section id="per-window-stability" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="per-window-stability"><span class="header-section-number">4.4</span> Per-Window Stability</h2>
<p>Toto’s per-window MAPE averaged 22.9% across 158 rolling windows, consistent with the aggregate MAPE (19.5%). This stability confirms the model does not rely on favorable test periods. Window 152 (MAPE=100.9%) corresponds to a traffic anomaly on June 2-8, 2026, demonstrating that even foundation models struggle with unprecedented events. The full-year context improved per-window MAPE from 23.2% (320h context) to 22.9% (8,704h context), confirming that seasonal patterns spanning months are critical for accurate forecasting.</p>
<div id="cell-window-analysis" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="window-analysis" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="paper_files/figure-html/window-analysis-output-1.png" width="1143" height="374" class="figure-img"></p>
<figcaption>Toto per-window MAPE across 158 rolling windows</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="uncertainty-calibration" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="uncertainty-calibration"><span class="header-section-number">4.5</span> Uncertainty Calibration</h2>
<p>Toto-2.0 outputs native 9-level quantile forecasts (replacing the Student-t head from Toto-1.0). We evaluate whether an observability-telemetry model can produce well-calibrated uncertainty intervals on a completely unseen domain. Using the 80% prediction interval (q10–q90), we compute Empirical Coverage, Empirical Coverage Error (ECE), and the Winkler Score.</p>
<p><strong>Hourly</strong>: Toto achieves 82.3% empirical coverage against an 80% nominal target (ECE = 2.3%), with a mean interval width of 162 vehicles/hour. This near-nominal calibration is remarkable for a zero-shot cross-domain transfer – the model’s quantile estimates, learned from CPU utilization and request latency distributions, generalize to traffic volume uncertainty.</p>
<p><strong>Daily</strong>: Aggregated to daily totals, coverage rises to 91.4% (ECE = 11.4%), indicating conservative intervals. This is expected: summing 24 hourly intervals causes errors to partially cancel, widening the effective interval relative to the aggregated point forecast.</p>
<p>These results suggest that foundation model quantile heads capture not just point patterns but also the <em>structure of uncertainty</em> across domains – a finding with implications for production deployment where reliable confidence intervals are as critical as point accuracy.</p>
</section>
<section id="horizon-stress-test-cpm-error-growth" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="horizon-stress-test-cpm-error-growth"><span class="header-section-number">4.6</span> Horizon Stress-Test: CPM Error Growth</h2>
<p>Toto-2.0’s Contiguous Patch Masking (CPM) decodes the entire horizon in one parallel forward pass, replacing autoregressive token-by-token generation. We stress-test this architecture by stretching the horizon to 320h (2 weeks) and 672h (4 weeks) while keeping the 8,704h context fixed. Two complementary analyses are presented.</p>
<section id="cpm-stress-test-rolling-windows" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="cpm-stress-test-rolling-windows"><span class="header-section-number">4.6.1</span> CPM Stress-Test (Rolling Windows)</h3>
<p>Averaging across all 158 rolling windows, Toto’s error grows gradually with horizon depth:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Horizon</th>
<th>1wk</th>
<th>2wk</th>
<th>3wk</th>
<th>4wk</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Toto h160</td>
<td>58.4</td>
<td>–</td>
<td>–</td>
<td>–</td>
</tr>
<tr class="even">
<td>Toto h320</td>
<td>59.2</td>
<td>88.0</td>
<td>–</td>
<td>–</td>
</tr>
<tr class="odd">
<td>Toto h672</td>
<td>59.2</td>
<td>95.5</td>
<td>141.8</td>
<td>172.2</td>
</tr>
</tbody>
</table>
<p>The 1-week MAE is stable at ~59 across all horizon lengths, confirming CPM’s parallel decoding: extending the horizon does not degrade short-range accuracy. Error roughly doubles by week 3 (141.8) and triples by week 4 (172.2), consistent with attention-based predictions lacking explicit periodic constraints beyond the training distribution.</p>
</section>
<section id="single-origin-comparison-no-re-scoring" class="level3" data-number="4.6.2">
<h3 data-number="4.6.2" class="anchored" data-anchor-id="single-origin-comparison-no-re-scoring"><span class="header-section-number">4.6.2</span> Single-Origin Comparison (No Re-Scoring)</h3>
<p>To isolate long-horizon degradation without the sliding-window advantage, we compare all models fitted once on ~8,700h of context from a single origin (2026-01-08, second week of January), with no re-scoring. This origin was chosen so that all models’ contexts include the January 1-2 holiday period, ensuring fair comparison.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="data/plots/horizon_comparison.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Horizon stress-test: error growth by forecast depth</figcaption>
</figure>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>1wk</th>
<th>2wk</th>
<th>3wk</th>
<th>4wk</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Toto-2.5B</td>
<td>31.6</td>
<td>126.4</td>
<td>273.6</td>
<td>259.0</td>
</tr>
<tr class="even">
<td>SARIMA</td>
<td>66.1</td>
<td>55.9</td>
<td>85.7</td>
<td>55.9</td>
</tr>
<tr class="odd">
<td>MSTL+ARIMA</td>
<td>45.2</td>
<td>45.0</td>
<td>75.7</td>
<td>41.4</td>
</tr>
<tr class="even">
<td>Naive</td>
<td>83.4</td>
<td>69.6</td>
<td>91.2</td>
<td>73.0</td>
</tr>
</tbody>
</table>
<p><strong>Short horizon (1 week)</strong>: Toto dominates at 31.6 MAE – 30% lower than MSTL+ARIMA (45.2) and 52% lower than SARIMA (66.1). The model leverages the full 8,704h context to capture fine-grained seasonal patterns.</p>
<p><strong>Medium horizon (2-3 weeks)</strong>: AR models hold steady (MAE ~41-86) thanks to their parametric seasonal structure. Toto degrades rapidly (126 to 274) because its attention-based predictions lack explicit periodic constraints.</p>
<p><strong>Long horizon (4 weeks)</strong>: AR models remain substantially better (41-73 vs.&nbsp;259). Toto’s error more than octuples from week 1.</p>
<p><strong>Why the rolling average differs</strong>: Toto’s production protocol re-scores every 24h with fresh context. Averaged across 158 rolling windows, the 1-week MAE is 59.2 – higher than the single-origin value (31.6) because different windows span periods of varying difficulty (seasonal transitions, special events). Continuous re-scoring means Toto never actually forecasts beyond 1 week in production – each prediction benefits from updated context that captures recent patterns. The AR models, fitted once, cannot adapt to distribution shifts.</p>
<p>Inference time remains flat at 0.2s per window regardless of horizon (160h vs.&nbsp;672h), confirming CPM’s O(1) decoding complexity.</p>
</section>
</section>
</section>
<section id="discussion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Discussion</h1>
<section id="why-toto-outperformed" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="why-toto-outperformed"><span class="header-section-number">5.1</span> Why Toto Outperformed</h2>
<section id="scaling-laws-for-time-series" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="scaling-laws-for-time-series"><span class="header-section-number">5.1.1</span> Scaling Laws for Time Series</h3>
<p>Toto’s 2.5B parameters, trained on 2+ trillion time series tokens, learned universal patterns of seasonality, trend, and noise that transfer across domains. The model’s ability to capture traffic patterns zero-shot suggests that <strong>time series structure is more universal than previously assumed</strong>. The attention mechanism can identify relevant historical patterns without parametric constraints on seasonality order or period.</p>
</section>
<section id="sliding-window-adaptation" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="sliding-window-adaptation"><span class="header-section-number">5.1.2</span> Sliding Window Adaptation</h3>
<p>Toto receives fresh context every 24 hours, implicitly adapting to recent patterns. The R models, fitted on fixed 8,760-hour windows, cannot adapt to distribution shifts within the test period. This is a methodological advantage of the sliding-window protocol, but it also reflects how foundation models would operate in production: continuously re-scoring with updated context.</p>
</section>
<section id="patch-based-architecture-with-long-context" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="patch-based-architecture-with-long-context"><span class="header-section-number">5.1.3</span> Patch-Based Architecture with Long Context</h3>
<p>Toto’s <code>patch_size=32</code> allows efficient processing of 8,704 hours of context (272 patches), capturing daily, weekly, monthly, and yearly seasonal patterns. The patching mechanism reduces sequence length while preserving local structure—a design choice that proves critical for capturing long-range dependencies in traffic data. Increasing context from 320h to 8,704h improved MAE by 12% (52.9 → 46.5), confirming that seasonal patterns spanning months are essential for accurate forecasting.</p>
</section>
<section id="well-calibrated-cross-domain-uncertainty" class="level3" data-number="5.1.4">
<h3 data-number="5.1.4" class="anchored" data-anchor-id="well-calibrated-cross-domain-uncertainty"><span class="header-section-number">5.1.4</span> Well-Calibrated Cross-Domain Uncertainty</h3>
<p>The 82.3% empirical coverage on hourly 80% prediction intervals (ECE = 2.3%) demonstrates that Toto’s quantile head, trained on server telemetry, generalizes to traffic uncertainty. This is notable because uncertainty structure – the relationship between point forecasts and interval width – is domain-specific. The model’s ability to produce well-calibrated intervals zero-shot suggests that the <em>shape</em> of forecast uncertainty (wider during peaks, narrower during steady periods) is a universal property of time series that transfers across domains.</p>
</section>
<section id="sliding-window-the-key-to-production-advantage" class="level3" data-number="5.1.5">
<h3 data-number="5.1.5" class="anchored" data-anchor-id="sliding-window-the-key-to-production-advantage"><span class="header-section-number">5.1.5</span> Sliding Window: The Key to Production Advantage</h3>
<p>The horizon stress-test reveals a stark contrast between single-origin and rolling-window performance. From a single origin (2026-01-08), Toto’s MAE grows from 31.6 (1 week) to 273.6 (3 weeks), degrading faster than AR models whose parametric seasonality holds steady at ~41-86 MAE through week 4. However, in production, Toto’s sliding-window protocol re-scores every 24h with fresh context, so it never actually forecasts beyond 1 week. The rolling-window average across 158 origins shows a 1-week MAE of 59.2 – still competitive with AR models (45-66 at 1 week from single origin). This continuous adaptation is the practical differentiator: it converts Toto’s strong short-horizon accuracy into sustained out-of-sample performance, while AR models fitted on fixed context cannot adapt to distribution shifts or seasonal transitions.</p>
</section>
</section>
<section id="why-classical-methods-underperformed" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="why-classical-methods-underperformed"><span class="header-section-number">5.2</span> Why Classical Methods Underperformed</h2>
<section id="sarimas-parametric-constraints" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="sarimas-parametric-constraints"><span class="header-section-number">5.2.1</span> SARIMA’s Parametric Constraints</h3>
<p>The frozen ARIMA(2,0,2)(2,1,0)[24] order was selected on the last year of training data. While adequate for the training distribution, it cannot adapt to test-period shifts. Two rolling chunks failed due to NaN values in the context window, falling back to naive forecasts.</p>
</section>
<section id="mstlarima-daily-degradation" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="mstlarima-daily-degradation"><span class="header-section-number">5.2.2</span> MSTL+ARIMA Daily Degradation</h3>
<p>The Loess decomposition captures multi-seasonality well for short horizons, but summing 24 hourly forecasts into daily totals compounds error. The daily MAE (2,578) is 44.8% higher than the hourly MAE scaled by 24 (57.4 × 24 = 1,378), indicating significant error accumulation.</p>
</section>
<section id="no-test-period-adaptation" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="no-test-period-adaptation"><span class="header-section-number">5.2.3</span> No Test-Period Adaptation</h3>
<p>Neither R model adapts to distribution shifts within the test period. A true rolling re-fit every 24 hours would be computationally prohibitive (50+ minutes per chunk before optimization).</p>
</section>
</section>
<section id="limitations" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="limitations"><span class="header-section-number">5.3</span> Limitations</h2>
<ol type="1">
<li><strong>Single sensor</strong>: Results may not generalize to other locations with different traffic patterns</li>
<li><strong>Univariate input</strong>: We used only “All Directions” aggregated counts. Multivariate input (all 6 lanes) showed nearly identical performance (MAE 58.7 vs 58.4), suggesting the univariate signal is sufficient for this sensor</li>
<li><strong>No fine-tuning baseline</strong>: We cannot quantify how much fine-tuning would improve Toto’s performance</li>
<li><strong>GPU requirement</strong>: The 8,704-hour context requires GPU acceleration (0.2s/window on RTX 3090). CPU inference would be ~4.5x slower but still feasible</li>
<li><strong>Horizon evaluation depth</strong>: The horizon stress-test evaluates 4-week-ahead forecasts using individual window segments, but the sliding-window protocol means each point has multiple overlapping forecasts. The single-origin comparison (2026-01-08) avoids the New Year’s Day holiday present at the test period boundary</li>
<li><strong>Context asymmetry</strong>: Toto’s context (8,704h, starting 2025-01-03) excludes January 1-2, 2025, while R models’ context (8,760h, starting 2025-01-01) includes it. This 56-hour difference is minor but means R models have slightly more holiday data in context</li>
<li><strong>Holiday and special events</strong>: The zero-shot model has no mechanism to incorporate external calendars or event information. A fine-tuned model with exogenous features (holidays, weather, special events) would likely perform better on anomalous periods</li>
</ol>
</section>
<section id="broader-implications" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="broader-implications"><span class="header-section-number">5.4</span> Broader Implications</h2>
<p>This experiment demonstrates that <strong>zero-shot foundation models can outperform classical methods on clean, highly seasonal data</strong>—a domain where SARIMA and TBATS were expected to dominate. The gap between “trained on X” and “works on Y” is narrower than previously assumed, suggesting that:</p>
<ul>
<li>Time series foundation models are ready for production forecasting</li>
<li>The value of domain-specific model selection may be smaller than traditionally believed</li>
<li>Foundation models offer a compelling alternative for organizations lacking statistical modeling expertise</li>
</ul>
</section>
</section>
<section id="conclusion" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Conclusion</h1>
<p>We presented the first comprehensive comparison of Toto-2.0-2.5B against classical methods on roadway traffic forecasting, with full context parity (8,704 hours for both model types). Contrary to expectations, the zero-shot foundation model outperformed SARIMA, MSTL+ARIMA, and seasonal naive on both hourly and daily horizons. The daily margin (67% lower MAE) is particularly striking, as it reflects better composability of hourly forecasts and superior capture of yearly seasonal patterns.</p>
<p>These results challenge the assumption that classical methods dominate on structured seasonal data. They also demonstrate that scaling laws for time series enable genuine cross-domain generalization—from server metrics to roadway traffic. Critically, increasing context from 13 days to 1 year improved Toto’s MAE by 12%, confirming that long-range dependencies are essential for accurate forecasting. The well-calibrated uncertainty intervals (82.3% coverage for 80% nominal) demonstrate that quantile heads transfer across domains. The horizon stress-test reveals a nuanced picture: Toto dominates at 1-week horizons from a single origin (31.6 vs.&nbsp;45.2 MAE), but degrades faster than AR models at 2-3 weeks (273.6 vs.&nbsp;75.7 MAE), showing that the sliding-window protocol (re-scoring every 24h with fresh context) is the practical mechanism that converts short-horizon dominance into sustained accuracy. As foundation models grow larger and gain fine-tuning support, the gap will only widen.</p>
<p>For practitioners, the message is clear: <strong>zero-shot foundation models are production-ready for time series forecasting</strong>. The ability to achieve state-of-the-art results without domain expertise, model selection, or hyperparameter tuning represents a paradigm shift in accessible forecasting. With GPU acceleration, inference runs at 0.2s/forecast regardless of horizon length (CPM’s O(1) decoding)—fast enough for real-time deployment.</p>
</section>
<section id="references" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> References</h1>
<ol type="1">
<li>Khwaja, E. et al.&nbsp;(2026). “Toto 2.0: Time Series Forecasting Enters the Scaling Era.” arXiv:2605.20119.</li>
<li>Hyndman, R.J. &amp; Athanasopoulos, G. (2021). “Forecasting: Principles and Practice.” OTexts, 3rd ed.</li>
<li>De Livera, A.M., Hyndman, R.J., &amp; Snyder, R.D. (2011). “Forecasting time series with complex seasonal patterns using exponential smoothing.” Journal of the American Statistical Association, 106(496), 1513-1527.</li>
<li>Tang, Y. et al.&nbsp;(2023). “Time-Series Foundation Model as a Generalized Forecasting Method.” arXiv:2310.01506.</li>
<li>Zhou, H. et al.&nbsp;(2021). “Informer: Beyond Efficient Transformer for Long Sequence Time-Series Forecasting.” AAAI.</li>
<li>MaineDOT Traffic Data. Drakewell C2 Platform. https://mainedottrafficdata.drakewell.com</li>
</ol>
<hr>
<p><em>Code and data available at: https://github.com/nicklisac/toto-traffic-forecast</em></p>
<p><em>This research used computational resources totaling ~5 minutes of GPU time (RTX 3090, 24GB VRAM) and ~10 minutes of CPU time for classical models.</em></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>